'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace localhost1
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PrivateServicesSoap", [Namespace]:="http://www.dotnetjunkies.com")>  _
    Public Class PrivateServices
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Public mySoapHeaderValue As mySoapHeader
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/ProADONET/VBProvider/PrivateServices.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("mySoapHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dotnetjunkies.com/GetMySecret", RequestNamespace:="http://www.dotnetjunkies.com", ResponseNamespace:="http://www.dotnetjunkies.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMySecret() As String
            Dim results() As Object = Me.Invoke("GetMySecret", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetMySecret(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMySecret", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetMySecret(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dotnetjunkies.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.dotnetjunkies.com", IsNullable:=false)>  _
    Public Class mySoapHeader
        Inherits SoapHeader
        
        '<remarks/>
        Public Username As String
        
        '<remarks/>
        Public Password As String
    End Class
End Namespace
