'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace localhost
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TrivialFunToolsSoap", [Namespace]:="http://www.dotnetjunkies.com")>  _
    Public Class TrivialFunTools
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/ProADONET/VBProvider/TrivialFunTools.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dotnetjunkies.com/RandomNumberGenerator", RequestNamespace:="http://www.dotnetjunkies.com", ResponseNamespace:="http://www.dotnetjunkies.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RandomNumberGenerator(ByVal LowNumber As Integer, ByVal HighNumber As Integer) As Integer
            Dim results() As Object = Me.Invoke("RandomNumberGenerator", New Object() {LowNumber, HighNumber})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginRandomNumberGenerator(ByVal LowNumber As Integer, ByVal HighNumber As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RandomNumberGenerator", New Object() {LowNumber, HighNumber}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRandomNumberGenerator(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dotnetjunkies.com/GetAllMovieQuotes", RequestNamespace:="http://www.dotnetjunkies.com", ResponseNamespace:="http://www.dotnetjunkies.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllMovieQuotes() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetAllMovieQuotes", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetAllMovieQuotes(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAllMovieQuotes", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetAllMovieQuotes(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dotnetjunkies.com/AddMovieQuotes", RequestNamespace:="http://www.dotnetjunkies.com", ResponseNamespace:="http://www.dotnetjunkies.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddMovieQuotes(ByVal MovieQuotes As System.Data.DataSet) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("AddMovieQuotes", New Object() {MovieQuotes})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginAddMovieQuotes(ByVal MovieQuotes As System.Data.DataSet, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddMovieQuotes", New Object() {MovieQuotes}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddMovieQuotes(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dotnetjunkies.com/GetMovieQuoteObject", RequestNamespace:="http://www.dotnetjunkies.com", ResponseNamespace:="http://www.dotnetjunkies.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMovieQuoteObject() As MovieQuote
            Dim results() As Object = Me.Invoke("GetMovieQuoteObject", New Object(-1) {})
            Return CType(results(0),MovieQuote)
        End Function
        
        '<remarks/>
        Public Function BeginGetMovieQuoteObject(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetMovieQuoteObject", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetMovieQuoteObject(ByVal asyncResult As System.IAsyncResult) As MovieQuote
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),MovieQuote)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dotnetjunkies.com/GetComplexMovieObject", RequestNamespace:="http://www.dotnetjunkies.com", ResponseNamespace:="http://www.dotnetjunkies.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetComplexMovieObject() As ComplexMovie
            Dim results() As Object = Me.Invoke("GetComplexMovieObject", New Object(-1) {})
            Return CType(results(0),ComplexMovie)
        End Function
        
        '<remarks/>
        Public Function BeginGetComplexMovieObject(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetComplexMovieObject", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetComplexMovieObject(ByVal asyncResult As System.IAsyncResult) As ComplexMovie
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ComplexMovie)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dotnetjunkies.com")>  _
    Public Class MovieQuote
        
        '<remarks/>
        Public Quote As String
        
        '<remarks/>
        Public ActorOrCharacter As String
        
        '<remarks/>
        Public Movie As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dotnetjunkies.com")>  _
    Public Class Quote
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public ActorOrCharacter As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Value As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dotnetjunkies.com")>  _
    Public Class ComplexMovie
        
        '<remarks/>
        Public Quote As Quote
        
        '<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Movie As String
    End Class
End Namespace
